package bid.woou.common.singleTable.model;

import java.io.Serializable;

public class Friendlist implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendlist.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendlist.master
     *
     * @mbggenerated
     */
    private Integer master;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendlist.friendid
     *
     * @mbggenerated
     */
    private Integer friendid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table friendlist
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendlist.id
     *
     * @return the value of friendlist.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendlist.id
     *
     * @param id the value for friendlist.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendlist.master
     *
     * @return the value of friendlist.master
     *
     * @mbggenerated
     */
    public Integer getMaster() {
        return master;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendlist.master
     *
     * @param master the value for friendlist.master
     *
     * @mbggenerated
     */
    public void setMaster(Integer master) {
        this.master = master;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendlist.friendid
     *
     * @return the value of friendlist.friendid
     *
     * @mbggenerated
     */
    public Integer getFriendid() {
        return friendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendlist.friendid
     *
     * @param friendid the value for friendlist.friendid
     *
     * @mbggenerated
     */
    public void setFriendid(Integer friendid) {
        this.friendid = friendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendlist
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", master=").append(master);
        sb.append(", friendid=").append(friendid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}