package bid.woou.common.singleTable.model;

import java.io.Serializable;

public class Savemsg implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savemsg.sendid
     *
     * @mbggenerated
     */
    private Integer sendid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savemsg.getid
     *
     * @mbggenerated
     */
    private Integer getid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savemsg.msg
     *
     * @mbggenerated
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savemsg.trantype
     *
     * @mbggenerated
     */
    private Byte trantype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savemsg.time
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savemsg.resulttype
     *
     * @mbggenerated
     */
    private Byte resulttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savemsg.messagetype
     *
     * @mbggenerated
     */
    private Byte messagetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column savemsg.sendname
     *
     * @mbggenerated
     */
    private String sendname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table savemsg
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savemsg.sendid
     *
     * @return the value of savemsg.sendid
     *
     * @mbggenerated
     */
    public Integer getSendid() {
        return sendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savemsg.sendid
     *
     * @param sendid the value for savemsg.sendid
     *
     * @mbggenerated
     */
    public void setSendid(Integer sendid) {
        this.sendid = sendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savemsg.getid
     *
     * @return the value of savemsg.getid
     *
     * @mbggenerated
     */
    public Integer getGetid() {
        return getid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savemsg.getid
     *
     * @param getid the value for savemsg.getid
     *
     * @mbggenerated
     */
    public void setGetid(Integer getid) {
        this.getid = getid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savemsg.msg
     *
     * @return the value of savemsg.msg
     *
     * @mbggenerated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savemsg.msg
     *
     * @param msg the value for savemsg.msg
     *
     * @mbggenerated
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savemsg.trantype
     *
     * @return the value of savemsg.trantype
     *
     * @mbggenerated
     */
    public Byte getTrantype() {
        return trantype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savemsg.trantype
     *
     * @param trantype the value for savemsg.trantype
     *
     * @mbggenerated
     */
    public void setTrantype(Byte trantype) {
        this.trantype = trantype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savemsg.time
     *
     * @return the value of savemsg.time
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savemsg.time
     *
     * @param time the value for savemsg.time
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savemsg.resulttype
     *
     * @return the value of savemsg.resulttype
     *
     * @mbggenerated
     */
    public Byte getResulttype() {
        return resulttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savemsg.resulttype
     *
     * @param resulttype the value for savemsg.resulttype
     *
     * @mbggenerated
     */
    public void setResulttype(Byte resulttype) {
        this.resulttype = resulttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savemsg.messagetype
     *
     * @return the value of savemsg.messagetype
     *
     * @mbggenerated
     */
    public Byte getMessagetype() {
        return messagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savemsg.messagetype
     *
     * @param messagetype the value for savemsg.messagetype
     *
     * @mbggenerated
     */
    public void setMessagetype(Byte messagetype) {
        this.messagetype = messagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column savemsg.sendname
     *
     * @return the value of savemsg.sendname
     *
     * @mbggenerated
     */
    public String getSendname() {
        return sendname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column savemsg.sendname
     *
     * @param sendname the value for savemsg.sendname
     *
     * @mbggenerated
     */
    public void setSendname(String sendname) {
        this.sendname = sendname == null ? null : sendname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savemsg
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sendid=").append(sendid);
        sb.append(", getid=").append(getid);
        sb.append(", msg=").append(msg);
        sb.append(", trantype=").append(trantype);
        sb.append(", time=").append(time);
        sb.append(", resulttype=").append(resulttype);
        sb.append(", messagetype=").append(messagetype);
        sb.append(", sendname=").append(sendname);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}