package bid.woou.support.dao;

import bid.woou.support.model.Friendlist;
import bid.woou.support.model.FriendlistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FriendlistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendlist
     *
     * @mbggenerated
     */
    int countByExample(FriendlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendlist
     *
     * @mbggenerated
     */
    int deleteByExample(FriendlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendlist
     *
     * @mbggenerated
     */
    int insert(Friendlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendlist
     *
     * @mbggenerated
     */
    int insertSelective(Friendlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendlist
     *
     * @mbggenerated
     */
    List<Friendlist> selectByExample(FriendlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendlist
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Friendlist record, @Param("example") FriendlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendlist
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Friendlist record, @Param("example") FriendlistExample example);
}