package bid.woou.support.dao;

import bid.woou.support.model.Savemsg;
import bid.woou.support.model.SavemsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SavemsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savemsg
     *
     * @mbggenerated
     */
    int countByExample(SavemsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savemsg
     *
     * @mbggenerated
     */
    int deleteByExample(SavemsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savemsg
     *
     * @mbggenerated
     */
    int insert(Savemsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savemsg
     *
     * @mbggenerated
     */
    int insertSelective(Savemsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savemsg
     *
     * @mbggenerated
     */
    List<Savemsg> selectByExample(SavemsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savemsg
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Savemsg record, @Param("example") SavemsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table savemsg
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Savemsg record, @Param("example") SavemsgExample example);
}